name = "cufun_theory"
defaultTargets = ["CuFunTheory"]

[[require]]
name = "mathlib"
from = git "https://github.com/leanprover-community/mathlib4"

[[lean_lib]]
name = "CuFunTheory"
roots = ["CuFun"]
